CREATE TABLE BRANCH (
	BRANCH_NAME VARCHAR2(12),
	BRANCH_CITY VARCHAR2(10),
	ASSETS NUMBER(10),
	CONSTRAINT BRANCH_PK PRIMARY KEY (BRANCH_NAME)	
);

CREATE TABLE CUSTOMER (
	CUSTOMER_NAME VARCHAR2(20),
	CUSTOMER_STREET VARCHAR2(10),
	CUSTOMER_CITY VARCHAR2(10),
	CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_NAME)	
);

CREATE TABLE ACCOUNT (
	ACCOUNT_NUMBER VARCHAR2(7),
	BRANCH_NAME VARCHAR2(10),
	BALANCE NUMBER(10),
	CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_NUMBER),
	CONSTRAINT ACCOUNT_FK FOREIGN KEY (BRANCH_NAME) REFERENCES BRANCH (BRANCH_NAME)
);

CREATE TABLE LOAN (
	LOAN_NUMBER VARCHAR2(7),
	BRANCH_NAME VARCHAR2(12),
	AMOUNT NUMBER(10),
	CONSTRAINT LOAN_PK PRIMARY KEY (LOAN_NUMBER),
	CONSTRAINT LOAN_FK FOREIGN KEY (BRANCH_NAME) REFERENCES BRANCH (BRANCH_NAME)
);

CREATE TABLE DEPOSITOR (
	CUSTOMER_NAME VARCHAR2(20),
	ACCOUNT_NUMBER VARCHAR2(7),
	CONSTRAINT DEPOSITOR_PK PRIMARY KEY (CUSTOMER_NAME,ACCOUNT_NUMBER),
	CONSTRAINT DEPOSITOR_FK1 FOREIGN KEY (CUSTOMER_NAME) REFERENCES CUSTOMER (CUSTOMER_NAME),
	CONSTRAINT DEPOSITOR_FK2 FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES ACCOUNT (ACCOUNT_NUMBER)
);

CREATE TABLE BORROWER (
	CUSTOMER_NAME VARCHAR2(20),
	LOAN_NUMBER VARCHAR2(5),
	CONSTRAINT BORROWER_PK PRIMARY KEY (CUSTOMER_NAME,LOAN_NUMBER),
	CONSTRAINT BORROWER_FK1 FOREIGN KEY (CUSTOMER_NAME) REFERENCES CUSTOMER (CUSTOMER_NAME),
	CONSTRAINT BORROWER_FK2 FOREIGN KEY (LOAN_NUMBER) REFERENCES LOAN (LOAN_NUMBER)
);